// <auto-generated />
using System;
using App.Infrastructure.Presistance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260302113408_change_birthDate_to_dateOnly")]
    partial class change_birthDate_to_dateOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.Core.Entities.Identity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("ParentRoleId")
                        .HasColumnType("int");

                    b.Property<int>("ScopeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.HasIndex("ParentRoleId");

                    b.HasIndex("ScopeId");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Code = "SYS_ADMIN",
                            ConcurrencyStamp = "AE6C6754-0862-4EA2-8868-BF5C27E7AEF9",
                            Description = "System Administrator with full access",
                            IsDeleted = false,
                            Name = "SystemAdmin",
                            NormalizedName = "SYSTEMADMIN",
                            ScopeId = 1
                        },
                        new
                        {
                            Id = 101,
                            Code = "UNI_ADMIN",
                            ConcurrencyStamp = "B1A2C3D4-5E6F-7890-ABCD-EF1234567890",
                            Description = "University Administrator",
                            IsDeleted = false,
                            Name = "UniversityAdmin",
                            NormalizedName = "UNIVERSITYADMIN",
                            ScopeId = 2
                        },
                        new
                        {
                            Id = 102,
                            Code = "FAC_ADMIN",
                            ConcurrencyStamp = "D3C4E5F6-7081-9012-CDEF-345678901234",
                            Description = "Faculty Administrator",
                            IsDeleted = false,
                            Name = "FacultyAdmin",
                            NormalizedName = "FACULTYADMIN",
                            ScopeId = 3
                        },
                        new
                        {
                            Id = 103,
                            Code = "FAC_COORD",
                            ConcurrencyStamp = "E4D5F6A7-8192-0123-DEF4-456789012345",
                            Description = "Faculty Coordinator",
                            IsDeleted = false,
                            Name = "FacultyCoordinator",
                            NormalizedName = "FACULTYCOORDINATOR",
                            ParentRoleId = 102,
                            ScopeId = 3
                        },
                        new
                        {
                            Id = 104,
                            Code = "ACAD_ADV",
                            ConcurrencyStamp = "F5E6A7B8-9203-1234-EF45-567890123456",
                            Description = "Academic Advisor",
                            IsDeleted = false,
                            Name = "AcademicAdvisor",
                            NormalizedName = "ACADEMICADVISOR",
                            ParentRoleId = 102,
                            ScopeId = 3
                        },
                        new
                        {
                            Id = 105,
                            Code = "DEPT_ADMIN",
                            ConcurrencyStamp = "A6F7B8C9-0314-2345-F456-678901234567",
                            Description = "Department Administrator",
                            IsDeleted = false,
                            Name = "DepartmentHead",
                            NormalizedName = "DEPARTMENTHEAD",
                            ScopeId = 4
                        },
                        new
                        {
                            Id = 106,
                            Code = "DOCTOR",
                            ConcurrencyStamp = "B7A8C9D0-1425-3456-A567-789012345678",
                            Description = "Doctor/Professor",
                            IsDeleted = false,
                            Name = "Doctor",
                            NormalizedName = "DOCTOR",
                            ParentRoleId = 105,
                            ScopeId = 4
                        },
                        new
                        {
                            Id = 107,
                            Code = "INSTRUCTOR",
                            ConcurrencyStamp = "C8B9D0E1-2536-4567-B678-890123456789",
                            Description = "Instructor/Teaching Assistant",
                            IsDeleted = false,
                            Name = "Instructor",
                            NormalizedName = "INSTRUCTOR",
                            ParentRoleId = 106,
                            ScopeId = 4
                        },
                        new
                        {
                            Id = 110,
                            Code = "MAIN_STUDENT",
                            ConcurrencyStamp = "F1E2A3B4-5869-789A-E901-123456789012",
                            Description = "Main Stream Student",
                            IsDeleted = false,
                            Name = "MainStreamStudent",
                            NormalizedName = "MAINSTREAMSTUDENT",
                            ScopeId = 5
                        },
                        new
                        {
                            Id = 111,
                            Code = "GPA_STUDENT",
                            ConcurrencyStamp = "A2F3B4C5-6970-89AB-F012-234567890123",
                            Description = "GPA Student",
                            IsDeleted = false,
                            Name = "GPAStudent",
                            NormalizedName = "GPASTUDENT",
                            ScopeId = 5
                        });
                });

            modelBuilder.Entity("App.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDisabled");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Religion")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 100,
                            AccessFailedCount = 0,
                            BirthDate = new DateOnly(1, 1, 1),
                            ConcurrencyStamp = "F0DD1622-6D6B-4654-9F52-82EDE53E5AD8",
                            Email = "system-admin@manara.org",
                            EmailConfirmed = true,
                            Gender = 0,
                            IsDeleted = false,
                            IsDisabled = false,
                            LockoutEnabled = false,
                            Name = "",
                            NationalId = "",
                            NormalizedEmail = "SYSTEM-ADMIN@MANARA.ORG",
                            NormalizedUserName = "SYSTEM-ADMIN@MANARA.ORG",
                            PasswordHash = "AQAAAAIAAYagAAAAEE9EyJUN4Xz2bvn2+h3p+oAlYKNgZ0pdEOC/OGIcSmBUG2cPPtftxmy87pluEQ6pLw==",
                            PhoneNumberConfirmed = false,
                            Religion = 0,
                            SecurityStamp = "5965A8A5-ACBA-46EE-8612-4F0771FDFAB8",
                            TwoFactorEnabled = false,
                            UserName = "system-admin@manara.org"
                        });
                });

            modelBuilder.Entity("App.Core.Entities.Identity.RoleClaimOverride", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId", "FacultyId", "ClaimValue");

                    b.HasIndex("FacultyId");

                    b.ToTable("RoleClaimOverrides");
                });

            modelBuilder.Entity("App.Core.Entities.Identity.Scope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentScopeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentScopeId");

                    b.ToTable("Scopes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "System"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "University",
                            ParentScopeId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Faculty",
                            ParentScopeId = 2
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Department",
                            ParentScopeId = 3
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Program",
                            ParentScopeId = 4
                        });
                });

            modelBuilder.Entity("App.Core.Entities.Identity.UserClaimOverride", b =>
                {
                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ApplicationUserId", "ClaimValue");

                    b.ToTable("UserClaimOverrides");
                });

            modelBuilder.Entity("App.Core.Entities.Personnel.DepartmentUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("DepartmentUsers");
                });

            modelBuilder.Entity("App.Core.Entities.Personnel.FacultyUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("FacultyId");

                    b.ToTable("FacultyUsers");
                });

            modelBuilder.Entity("App.Core.Entities.Personnel.ProgramUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("ProgramId");

                    b.ToTable("ProgramUsers");
                });

            modelBuilder.Entity("App.Core.Entities.Personnel.UniversityUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("UniversityId");

                    b.ToTable("UniversityUsers");
                });

            modelBuilder.Entity("App.Core.Entities.Universities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("HeadOfDepartment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("App.Core.Entities.Universities.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("FAQ");
                });

            modelBuilder.Entity("App.Core.Entities.Universities.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("App.Core.Entities.Universities.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("App.Core.Entities.Universities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("App.Core.Entities.Universities.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("YearOfEstablishment")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Universities", t =>
                        {
                            t.HasCheckConstraint("CK_University_YearOfEstablishment", "[YearOfEstablishment] >= 1800 AND [YearOfEstablishment] <= YEAR(GETDATE())");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "permissions",
                            ClaimValue = "roles:read",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "permissions",
                            ClaimValue = "roles:create",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "permissions",
                            ClaimValue = "roles:update",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "permissions",
                            ClaimValue = "roles:toggleStatus",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "permissions",
                            ClaimValue = "permissions:read",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "permissions",
                            ClaimValue = "permissions:update",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "permissions",
                            ClaimValue = "permissions:create",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "permissions",
                            ClaimValue = "permissions:toggleStatus",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "permissions",
                            ClaimValue = "universities:read",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "permissions",
                            ClaimValue = "universities:create",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "permissions",
                            ClaimValue = "universities:update",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "permissions",
                            ClaimValue = "universities:toggleStatus",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "permissions",
                            ClaimValue = "faculties:read",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "permissions",
                            ClaimValue = "faculties:create",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "permissions",
                            ClaimValue = "faculties:update",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "permissions",
                            ClaimValue = "faculties:toggleStatus",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "permissions",
                            ClaimValue = "departments:read",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "permissions",
                            ClaimValue = "departments:create",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "permissions",
                            ClaimValue = "departments:update",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "permissions",
                            ClaimValue = "departments:toggleStatus",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "permissions",
                            ClaimValue = "Programs:read",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "permissions",
                            ClaimValue = "Programs:create",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 23,
                            ClaimType = "permissions",
                            ClaimValue = "Programs:update",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 24,
                            ClaimType = "permissions",
                            ClaimValue = "Programs:toggleStatus",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 25,
                            ClaimType = "permissions",
                            ClaimValue = "universityUsers:read",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 26,
                            ClaimType = "permissions",
                            ClaimValue = "universityUsers:create",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 27,
                            ClaimType = "permissions",
                            ClaimValue = "universityUsers:update",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 28,
                            ClaimType = "permissions",
                            ClaimValue = "universityUsers:toggleStatus",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 29,
                            ClaimType = "permissions",
                            ClaimValue = "facultyUsers:read",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 30,
                            ClaimType = "permissions",
                            ClaimValue = "facultyUsers:create",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 31,
                            ClaimType = "permissions",
                            ClaimValue = "facultyUsers:update",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 32,
                            ClaimType = "permissions",
                            ClaimValue = "facultyUsers:toggleStatus",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 33,
                            ClaimType = "permissions",
                            ClaimValue = "departmentUsers:read",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 34,
                            ClaimType = "permissions",
                            ClaimValue = "departmentUsers:create",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 35,
                            ClaimType = "permissions",
                            ClaimValue = "departmentUsers:update",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 36,
                            ClaimType = "permissions",
                            ClaimValue = "departmentUsers:toggleStatus",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 37,
                            ClaimType = "permissions",
                            ClaimValue = "programUsers:read",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 38,
                            ClaimType = "permissions",
                            ClaimValue = "programUsers:create",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 39,
                            ClaimType = "permissions",
                            ClaimValue = "programUsers:update",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 40,
                            ClaimType = "permissions",
                            ClaimValue = "programUsers:toggleStatus",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 41,
                            ClaimType = "permissions",
                            ClaimValue = "scopes:read",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 42,
                            ClaimType = "permissions",
                            ClaimValue = "scopes:readDetail",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 43,
                            ClaimType = "permissions",
                            ClaimValue = "scopes:create",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 44,
                            ClaimType = "permissions",
                            ClaimValue = "scopes:update",
                            RoleId = 100
                        },
                        new
                        {
                            Id = 45,
                            ClaimType = "permissions",
                            ClaimValue = "scopes:toggleStatus",
                            RoleId = 100
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 100,
                            RoleId = 100
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("App.Core.Entities.Identity.ApplicationRole", b =>
                {
                    b.HasOne("App.Core.Entities.Identity.ApplicationRole", "ParentRole")
                        .WithMany("ChildRoles")
                        .HasForeignKey("ParentRoleId");

                    b.HasOne("App.Core.Entities.Identity.Scope", "Scope")
                        .WithMany("Roles")
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentRole");

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("App.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.OwnsMany("App.Core.Entities.Identity.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ExpireOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("RevokedOn")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("RefreshTokens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("App.Core.Entities.Identity.RoleClaimOverride", b =>
                {
                    b.HasOne("App.Core.Entities.Universities.Faculty", "Faculty")
                        .WithMany("RoleClaimOverrides")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Core.Entities.Identity.ApplicationRole", "Role")
                        .WithMany("RoleClaimOverrides")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("App.Core.Entities.Identity.Scope", b =>
                {
                    b.HasOne("App.Core.Entities.Identity.Scope", "ParentScope")
                        .WithMany("ChildScopes")
                        .HasForeignKey("ParentScopeId");

                    b.Navigation("ParentScope");
                });

            modelBuilder.Entity("App.Core.Entities.Identity.UserClaimOverride", b =>
                {
                    b.HasOne("App.Core.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany("PermissionOverrides")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("App.Core.Entities.Personnel.DepartmentUser", b =>
                {
                    b.HasOne("App.Core.Entities.Universities.Department", "Department")
                        .WithMany("DepartmentUsers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Core.Entities.Identity.ApplicationUser", "User")
                        .WithOne("DepartmentUser")
                        .HasForeignKey("App.Core.Entities.Personnel.DepartmentUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Core.Entities.Personnel.FacultyUser", b =>
                {
                    b.HasOne("App.Core.Entities.Universities.Faculty", "Faculty")
                        .WithMany("FacultyUsers")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Core.Entities.Identity.ApplicationUser", "User")
                        .WithOne("FacultyUser")
                        .HasForeignKey("App.Core.Entities.Personnel.FacultyUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Core.Entities.Personnel.ProgramUser", b =>
                {
                    b.HasOne("App.Core.Entities.Universities.Program", "Program")
                        .WithMany("ProgramUsers")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Core.Entities.Identity.ApplicationUser", "User")
                        .WithOne("ProgramUser")
                        .HasForeignKey("App.Core.Entities.Personnel.ProgramUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Core.Entities.Personnel.UniversityUser", b =>
                {
                    b.HasOne("App.Core.Entities.Universities.University", "University")
                        .WithMany("UniversityUsers")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Core.Entities.Identity.ApplicationUser", "User")
                        .WithOne("UniversityUser")
                        .HasForeignKey("App.Core.Entities.Personnel.UniversityUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Core.Entities.Universities.Department", b =>
                {
                    b.HasOne("App.Core.Entities.Universities.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("App.Core.Entities.Universities.FAQ", b =>
                {
                    b.HasOne("App.Core.Entities.Universities.Subject", "Subject")
                        .WithMany("FAQs")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("App.Core.Entities.Universities.Faculty", b =>
                {
                    b.HasOne("App.Core.Entities.Universities.University", "University")
                        .WithMany("Faculties")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("App.Core.Entities.Universities.Program", b =>
                {
                    b.HasOne("App.Core.Entities.Universities.Department", "Department")
                        .WithMany("Programs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("App.Core.Entities.Universities.Subject", b =>
                {
                    b.HasOne("App.Core.Entities.Universities.Program", "Program")
                        .WithMany("Subjects")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("App.Core.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("App.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("App.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("App.Core.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("App.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Core.Entities.Identity.ApplicationRole", b =>
                {
                    b.Navigation("ChildRoles");

                    b.Navigation("RoleClaimOverrides");
                });

            modelBuilder.Entity("App.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("DepartmentUser")
                        .IsRequired();

                    b.Navigation("FacultyUser")
                        .IsRequired();

                    b.Navigation("PermissionOverrides");

                    b.Navigation("ProgramUser")
                        .IsRequired();

                    b.Navigation("UniversityUser")
                        .IsRequired();
                });

            modelBuilder.Entity("App.Core.Entities.Identity.Scope", b =>
                {
                    b.Navigation("ChildScopes");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("App.Core.Entities.Universities.Department", b =>
                {
                    b.Navigation("DepartmentUsers");

                    b.Navigation("Programs");
                });

            modelBuilder.Entity("App.Core.Entities.Universities.Faculty", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("FacultyUsers");

                    b.Navigation("RoleClaimOverrides");
                });

            modelBuilder.Entity("App.Core.Entities.Universities.Program", b =>
                {
                    b.Navigation("ProgramUsers");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("App.Core.Entities.Universities.Subject", b =>
                {
                    b.Navigation("FAQs");
                });

            modelBuilder.Entity("App.Core.Entities.Universities.University", b =>
                {
                    b.Navigation("Faculties");

                    b.Navigation("UniversityUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
